name: Deno

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run:
    runs-on: "windows-latest"

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - name: Run
        run: deno run --allow-net --allow-env --allow-read app.ts
        env:
          telegramApiToken: ${{ env.TELEGRAMAPITOKEN }}
          chatId: ${{ env.CHATID }}
          sessionId: ${{ env.SESSIONID }}
